[package]
name = "rustmith_backend"
version = "0.1.0"
authors = ["Eduard Knyshov <edvorg@gmail.com>"]
description = "Rocksmith clone for WEB platform"
edition = "2018"

[dependencies]
serde = "1.0.0"
serde_json = "1.0.0"
serde_derive = "1.0.0"
rustmith_common = { path = "../common" }